/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Stock.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#define PORT 10001

 // variables globales

int nbBallons =4;
char logs[6];
int code = 1; // ne pas oublier de l'incrémenter


char *IP="127.0.0.1"; // adresse provisoire, sera remplacée par l'IP du robot



// structure d'un ballon
struct ball{int ID; char IPjoueur[32]; int chrono};
typedef struct ball ball;

// tableau des ballons

char* Ballons[4]={"blabla*bla*0","blabla*bla*0","blabla*bla*0","blabla*bla*0"};

//fonction récupération logs (inutile ?)


// fonction verification même ballon
int sameball(char* Ballon1, char* Ballon2){
	
	return strcmp(Ballon1,Ballon2);
}
// fonction qui récupère le chrono de la clé Ballon
int chronoBall(char *cleballon){
	char *token;
	const char s[2] = "*";
	token = strtok(cleballon,s); // récupération de L'ID
	token = strtok(NULL,s); // récupération de l'IP
	token = strtok(NULL,s); // récupération de l'heure en seconde
	int chrono = atoi(token);
	return chrono;
}

//fonction ballons dispos --> test

int ballonDispo(){
	int temps = time(NULL);
	int ballonlibre=-1; // valeur arbitraire (il n'y a que 4 ballons possibles)
	int j = 0;
	
	// regarde si il y a des ballons dispos ou si ils ont expiré
	while( j<sizeof(Ballons) && ballonlibre == -1){	
		if(chronoBall(Ballons[j]) <= temps -120){
			ballonlibre=j;
		}
		j++;
	}
	return ballonlibre;
}

	/*function qui génère un ballon à distribuer*/
ball GenerateBall(char *IPjoueur){

  ball Ballon;
  strcpy(Ballon.IPjoueur,IPjoueur);
  /*Initialisation pour la date en seconde*/
  time_t temps;
  time(&temps);

 Ballon.chrono = temps;

  Ballon.ID = code;
  return Ballon;
}


//fonction distribution ballon : appel ballon dispo en renvoie toujours 1 (décrément nb ballon)

char* distribBallon(char * IPjoueur){
	int estdispo = 0;
	int j=-1;
	ball Ballon;
	while( j==-1){
		j = ballonDispo();
		sleep(100);
	}
	Ballon = GenerateBall(IPjoueur);
	char* cleBallon = Serialize(Ballon);
	return cleBallon;
}


// fonction validation ballon --> en libère un si true

int ballonvalide(char* Ballon){
	int i = 0;
	int trouve = 0;
	while(i < sizeof(Ballons) && trouve == 0){
    // test si le ball est dans la liste de Ballons et si il n'est pas encore expiré
	    if( sameball(Ballons[i], Ballon) && chronoBall(Ballon) + 120 >= time(NULL)){
	        Ballons[i] = Ballon;
	        nbBallons +=1;
	        trouve = 1;
		}
	}
	return trouve;
}


reponse1 *
validation_1_svc(data1 *argp, struct svc_req *rqstp)
{
	static reponse1  result;

	int same = 0;



	return &result;
}

reponse2 *
distribution_2_svc(data2 *argp, struct svc_req *rqstp)
{
	static reponse2  result;

	/*
	 * insert server code here
	 */

	return &result;
}
