/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "Stock.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

reponse1 *
validation_1(data1 *argp, CLIENT *clnt)
{
	static reponse1 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Validation,
		(xdrproc_t) xdr_data1, (caddr_t) argp,
		(xdrproc_t) xdr_reponse1, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reponse2 *
distribution_2(data2 *argp, CLIENT *clnt)
{
	static reponse2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, distribution,
		(xdrproc_t) xdr_data2, (caddr_t) argp,
		(xdrproc_t) xdr_reponse2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
