/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STOCK_H_RPCGEN
#define _STOCK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data1 {
	int ballonDispo;
};
typedef struct data1 data1;


struct reponse1 {
	char cleballon[256];
};
typedef struct reponse1 reponse1;


struct data2 {
	char cleballon[256];
};
typedef struct data2 data2;


struct reponse1 {
	int ok;
};
typedef struct reponse1 reponse1;


#define Validation 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define Validation 1
extern  reponse1 * validation_1(data1 *, CLIENT *);
extern  reponse1 * validation_1_svc(data1 *, struct svc_req *);
extern int validation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Validation 1
extern  reponse1 * validation_1();
extern  reponse1 * validation_1_svc();
extern int validation_1_freeresult ();
#endif /* K&R C */

#define distribution 0x20000001
#define VERSION_UN 2

#if defined(__STDC__) || defined(__cplusplus)
#define distribution 1
extern  reponse2 * distribution_2(data2 *, CLIENT *);
extern  reponse2 * distribution_2_svc(data2 *, struct svc_req *);
extern int distribution_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define distribution 1
extern  reponse2 * distribution_2();
extern  reponse2 * distribution_2_svc();
extern int distribution_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);
extern  bool_t xdr_data2 (XDR *, data2*);
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);

#else /* K&R C */
extern bool_t xdr_data1 ();
extern bool_t xdr_data1 ();
extern bool_t xdr_reponse1 ();
extern bool_t xdr_reponse1 ();
extern bool_t xdr_data2 ();
extern bool_t xdr_data1 ();
extern bool_t xdr_reponse1 ();
extern bool_t xdr_reponse1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STOCK_H_RPCGEN */
