/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Validation.h"

reponse *
validation_1_svc(data *argp, struct svc_req *rqstp)
{
	static reponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}